/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.4-154-g79c114e1b2-20210930"
#endif /* AVUTIL_FFVERSION_H */
